//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TreeViewDemo.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OrganizationEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OrganizationEntities object using the connection string found in the 'OrganizationEntities' section of the application configuration file.
        /// </summary>
        public OrganizationEntities() : base("name=OrganizationEntities", "OrganizationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OrganizationEntities object.
        /// </summary>
        public OrganizationEntities(string connectionString) : base(connectionString, "OrganizationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OrganizationEntities object.
        /// </summary>
        public OrganizationEntities(EntityConnection connection) : base(connection, "OrganizationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employees
        {
            get
            {
                if ((_Employees == null))
                {
                    _Employees = base.CreateObjectSet<Employee>("Employees");
                }
                return _Employees;
            }
        }
        private ObjectSet<Employee> _Employees;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OrganizationModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="emp_Code">Initial value of the Emp_Code property.</param>
        public static Employee CreateEmployee(global::System.String emp_Code)
        {
            Employee employee = new Employee();
            employee.Emp_Code = emp_Code;
            return employee;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Emp_Code
        {
            get
            {
                return _Emp_Code;
            }
            set
            {
                if (_Emp_Code != value)
                {
                    OnEmp_CodeChanging(value);
                    ReportPropertyChanging("Emp_Code");
                    _Emp_Code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Emp_Code");
                    OnEmp_CodeChanged();
                }
            }
        }
        private global::System.String _Emp_Code;
        partial void OnEmp_CodeChanging(global::System.String value);
        partial void OnEmp_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reporting
        {
            get
            {
                return _Reporting;
            }
            set
            {
                OnReportingChanging(value);
                ReportPropertyChanging("Reporting");
                _Reporting = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reporting");
                OnReportingChanged();
            }
        }
        private global::System.String _Reporting;
        partial void OnReportingChanging(global::System.String value);
        partial void OnReportingChanged();

        #endregion

    
    }

    #endregion

    
}
